name: Jenkins # Name of the Catalog Entry
description: |
  Jenkins CI server (LTS) # Description of the Catalog Entry
version: 2.9.5-rancher1 # Version of the Catalog to be used
category: Continuous Integration # Category to be used for searching catalog entries
maintainer: Markus Meixner # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
